sonar.projectKey=eimmig_sv-telegram-integration-backend
sonar.sources=.
sonar.exclusions=**/tests/**,**/.venv/**
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
