"""HTTP client for the direct call to auth-service that confirms a Telegram account
link. This call bypasses the api-gateway (see docs/DECISIONS-LOG.md 2026-09-08):
api-gateway does not route /api/v1/telegram-accounts/**, and its
ServiceKeyAuthenticationFilter requires an already-confirmed link to resolve identity,
which is circular for the endpoint that creates the link. The one-time link code itself
(generated by auth-service, short TTL) is this call's security mechanism.
"""

from __future__ import annotations

import logging
import os
from enum import Enum, auto

import httpx

logger = logging.getLogger(__name__)

_TIMEOUT_SECONDS = 5.0


class LinkOutcome(Enum):
    SUCCESS = auto()
    CODE_NOT_FOUND = auto()
    CODE_EXPIRED = auto()
    ALREADY_LINKED = auto()
    SERVICE_UNAVAILABLE = auto()


_STATUS_TO_OUTCOME = {
    201: LinkOutcome.SUCCESS,
    404: LinkOutcome.CODE_NOT_FOUND,
    422: LinkOutcome.CODE_EXPIRED,
    409: LinkOutcome.ALREADY_LINKED,
}


def _auth_service_url() -> str:
    return os.environ.get("AUTH_SERVICE_URL", "http://localhost:8081")


def confirm_telegram_link(telegram_user_id: str, code: str, correlation_id: str) -> LinkOutcome:
    try:
        response = httpx.post(
            f"{_auth_service_url()}/api/v1/telegram-accounts",
            json={"telegramUserId": telegram_user_id, "code": code},
            headers={"X-Correlation-Id": correlation_id},
            timeout=_TIMEOUT_SECONDS,
        )
    except httpx.HTTPError:
        logger.warning("auth-service unreachable confirming telegram link [correlationId=%s]", correlation_id)
        return LinkOutcome.SERVICE_UNAVAILABLE

    outcome = _STATUS_TO_OUTCOME.get(response.status_code)
    if outcome is None:
        logger.warning(
            "unexpected auth-service status %s confirming telegram link [correlationId=%s]",
            response.status_code,
            correlation_id,
        )
        return LinkOutcome.SERVICE_UNAVAILABLE
    return outcome
